"use client";
import { useState,type FormEvent } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { useLanguage } from "@/lib/i18n/provider";
import type { PlanRow,WorkspaceData } from "@/lib/finance/records";

export default function PlanDetailsEditor({ plan,data,userId,supabase,onSaved,onCancel }: { plan: PlanRow; data: WorkspaceData; userId: string; supabase: SupabaseClient; onSaved: () => Promise<void>; onCancel: () => void }) {
  const { locale }=useLanguage(); const text=(ko:string,en:string)=>locale==="ko"?ko:en;
  const [title,setTitle]=useState(plan.title); const [date,setDate]=useState(plan.scheduled_date);
  const [account,setAccount]=useState(plan.account_id??""); const [category,setCategory]=useState(plan.category_id??"");
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function save(event:FormEvent){event.preventDefault();const parsed=new Date(`${date}T00:00:00Z`);if(!title.trim()||title.trim().length>500||Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==date){setMessage(text("제목과 날짜를 확인하세요.","Check the title and date."));return;}setBusy(true);try{const result=await supabase.from("plans").update({title:title.trim(),scheduled_date:date,account_id:account||null,category_id:category||null}).eq("id",plan.id).eq("user_id",userId).eq("title",plan.title).eq("scheduled_date",plan.scheduled_date).select("id");if(result.error||!result.data?.length)throw new Error("Not saved");await onSaved();}catch{setMessage(text("저장하지 못했습니다. 다른 화면의 변경을 확인하고 다시 불러오세요.","Not saved. Check concurrent changes and reload."));}finally{setBusy(false);}}
  return <form onSubmit={save} className="my-3 grid gap-3 rounded border border-teal-200 bg-teal-50 p-3 sm:grid-cols-2" aria-label={text("계획 정보 수정","Edit plan details")}><p className="text-sm sm:col-span-2">{text("제목·예정일·연결 계좌·분류를 수정합니다. 최초 계획 금액과 환율 기록은 보존됩니다. 현재 예상 환율·수수료는 ‘환율·수수료 수정’에서 변경하세요.","Edit title, due date, account and category. Original planned amounts and FX evidence are preserved. Use Revise FX / fee to change the forecast.")}</p><label>{text("제목","Title")}<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label>{text("예정일","Due date")}<input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label>{text("계좌","Account")}<select value={account} onChange={e=>setAccount(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">{text("미지정","Unassigned")}</option>{data.accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{text("분류","Category")}<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">{text("미분류","Uncategorized")}</option>{data.categories.filter(c=>c.is_active&&c.normal_direction===plan.direction).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{message&&<p role="alert" className="text-red-700 sm:col-span-2">{message}</p>}<div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="rounded bg-teal-700 px-3 py-2 text-white">{text("수정 저장","Save changes")}</button><button type="button" disabled={busy} onClick={onCancel} className="underline">{text("취소","Cancel")}</button></div></form>;
}
